version: '3'
services:


  db:
     container_name: Database
     image: postgres
     volumes:
       - ./data:/var/lib/pgsql/data
     environment:
       - POSTGRES_DB=post
       - POSTGRES_USER=test
       - POSTGRES_PASSWORD=test
       - PGDATA=/var/lib/pgsql/data/pgdata

  web:
    container_name: Web-app
    build: ./code
    command: bash -C "python3 manage.py makemigrations &&
            python3 manage.py migrate && python3 manage.py collectstatic --noinput &&
            gunicorn mysite.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - ./code:/code
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=verystrongpasswd
    links:
      - "db:db"
    ports:
      - 8001:8001
